defaults:
  run:
    working-directory: ./GNSSLogger
jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew test check connectedCheck -x lint --stacktrace
        working-directory: ./GNSSLogger
    strategy:
      matrix:
        api-level:
        - 24
        - 29
name: Android CI Build
on:
  repository_dispatch:
    types: trigger-ga___android.yml
